### ISSUE TITLE
Proper version tagging

### ISSUE THREAD

**Issue by ruzickap** [azohra/shell-linter#20]
Hello.

Would it be possible to do a proper tagging for this project please? 

Maybe good starting point is here: https://github.com/actions/checkout 
They are using versions like:

* `v2` -> `v2.1.0`
* `v1` -> `v1.3.0`

It would be really handy to use something like `v1` instead of specifying the exact version only `v1.3.0`:

```yaml
    - uses: azohra/shell-linter@v1
```

It will save me from changing the "exact versions" when you release new version.

Thank you...

**Comment by Azbagheri** [comment]
@ruzickap Thank you so much for pointing out the major version binding recommended by Github. We are indeed following Semantic Versioning, and as much as we love the idea of major version binding, we find it inappropriate to bump the major version of the shell-linter action at this point as it hints a backward incompatible change according to SemVer. With that said, when the time comes, we will definitely use the major version tags for this action. 

To address your request, however, we have added a 'latest' tag that points to the latest stable version of the shell-linter action. This change has already been released which means you can now use our "latest" version instead of the exact versions as following:
```yml
      - name: Lint check
        uses: azohra/shell-linter@latest
```
Please do not hesitate to let me know if you have any questions or concerns.

**Comment by ruzickap** [comment]
Thanks a lot...

I'm going to close it for now...
